// <auto-generated />
using AllocationApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace AllocationApp.Migrations
{
    [DbContext(typeof(AllocationDBContext))]
    [Migration("20180321124602_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("AllocationApp.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AllocationApp.Models.CourseWork", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourseId1");

                    b.Property<string>("CourseName");

                    b.Property<int>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseId1");

                    b.ToTable("CourseWork");
                });

            modelBuilder.Entity("AllocationApp.Models.Hour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourseIdId");

                    b.Property<string>("Date");

                    b.Property<int>("HourType");

                    b.Property<bool>("IsApproved");

                    b.Property<int>("PayRate");

                    b.Property<int?>("UserIdId");

                    b.HasKey("Id");

                    b.HasIndex("CourseIdId");

                    b.HasIndex("UserIdId");

                    b.ToTable("Hour");
                });

            modelBuilder.Entity("AllocationApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("AllocationApp.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourseId");

                    b.Property<int?>("UserId");

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("AllocationApp.Models.Subordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("firstname")
                        .IsRequired();

                    b.Property<string>("occupation")
                        .IsRequired();

                    b.Property<string>("surname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Subordinates");
                });

            modelBuilder.Entity("AllocationApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AllocationApp.Models.Course", b =>
                {
                    b.HasOne("AllocationApp.Models.User")
                        .WithMany("Courses")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AllocationApp.Models.CourseWork", b =>
                {
                    b.HasOne("AllocationApp.Models.Course")
                        .WithMany("Lecturers")
                        .HasForeignKey("CourseId1");
                });

            modelBuilder.Entity("AllocationApp.Models.Hour", b =>
                {
                    b.HasOne("AllocationApp.Models.Course", "CourseId")
                        .WithMany()
                        .HasForeignKey("CourseIdId");

                    b.HasOne("AllocationApp.Models.User", "UserId")
                        .WithMany("WorkHours")
                        .HasForeignKey("UserIdId");
                });

            modelBuilder.Entity("AllocationApp.Models.Role", b =>
                {
                    b.HasOne("AllocationApp.Models.User")
                        .WithMany("RoleType")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AllocationApp.Models.Skill", b =>
                {
                    b.HasOne("AllocationApp.Models.Course")
                        .WithMany("Requirements")
                        .HasForeignKey("CourseId");

                    b.HasOne("AllocationApp.Models.User")
                        .WithMany("Skills")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
